Added conversion to light-seconds
cannawen/metric_units_reddit_bot pull request #37
Opened 2017-10-03 09:00 UTC by Doomki

2017-10-03 12:45 UTC, cannawen requested changes
Looks good, thanks for the spelling and formatting fixes! Can you add a test for light-seconds as well?

2017-10-04 09:21 UTC, Doomki commented
Ok I added the test, it seems to work as intended.

2017-10-04 12:05 UTC, cannawen approved these changes

2017-10-04 12:06 UTC, merged

2017-10-04 12:07 UTC, cannawen commented
Awesome, thanks for the PR! Your change will be in bot v0.11.5 :)